"""What the session was for, out of what the person typed.

The digest could say how many commands ran and not one word about what any of
them was *for*.  Nobody answers "what did you build today?" with a count of
shell invocations, so the digest was answering a question nobody asks.

The goal of a session is already written down.  Somebody typed it, at the top,
before any of the work happened.  This module is the small amount of work
between that text and a line worth reading.

What comes back is one line, not the conversation.  A session's prompts are
mostly follow-ups -- "ok", "yes", "now the other one" -- and the one that names
the work is nearly always the first with something in it.  On the 307
transcripts on this machine, 93 of 117 first prompts were already prose and the
rest were slash-command stubs, which is the one shape worth dropping.

The parser calls this at the two points where it has *already* decided a record
is a person typing rather than the agent feeding itself, so nothing here has to
work that out again.  See the comment above ``s["user_turns"] += 1``.
"""

from __future__ import annotations

import re
from typing import Iterable, List, Optional

#: How much of one prompt is kept.  A prompt can be a page; what is being
#: stored is the sentence that names the work, and the renderers cut it again
#: to whatever room their row has.  Kept generous so the cut is theirs.
MAX_CHARS = 400

#: A word count below which a prompt is not naming any work.  One word is
#: "ok" or "continue"; two is "run agentlog", which is a goal.
MIN_WORDS = 2

#: One-word replies that are agreement, not an instruction.  They pass the word
#: count only when somebody types "ok then", which is fine -- these are the
#: ones that show up alone.
_ACKNOWLEDGEMENTS = frozenset("""
ok okay k yes yep yeah y no nope n sure thanks thx ty please go continue
proceed next done fine good great cool right correct exactly agreed
""".split())

#: Claude Code writes into the conversation on its own account, and most of
#: what it writes is wrapped in one of these.  The parser's ``isMeta`` check
#: catches nearly all of it; this catches the rest, because a stub that got
#: through would be printed as though somebody had typed it.
_TAG_BLOCK = re.compile(
    r"<(command-name|command-message|command-args|command-contents|"
    r"local-command-stdout|local-command-stderr|system-reminder|"
    r"user-prompt-submit-hook|task-notification)\b[^>]*>.*?</\1>",
    re.DOTALL | re.IGNORECASE,
)
_LONE_TAG = re.compile(r"</?[a-z][a-z0-9-]*\b[^>]*/?>", re.IGNORECASE)

#: Preambles the harness prepends to a real prompt.  Each is the start of a
#: paragraph the person did not write, sitting in front of one they did, so
#: what is dropped is the paragraph and not the record.
_PREAMBLES = (
    "caveat: the messages below were generated by the user while running",
    "this session is being continued from a previous conversation",
    "the user sent a new message while you were working",
    "[request interrupted",
)


def the_ask(text: Optional[str]) -> str:
    """One typed prompt, cleaned down to the line that could be printed.

    Returns ``""`` for anything that is not somebody asking for something --
    a slash-command stub, a harness preamble, whitespace.  The caller is
    expected to keep asking with the next prompt rather than to give up.
    """
    if not text:
        return ""
    body = _TAG_BLOCK.sub(" ", text)
    body = _LONE_TAG.sub(" ", body)
    body = body.replace(" ", " ")

    # A preamble is a paragraph, so drop paragraphs rather than the record: the
    # prompt underneath one is the whole reason the record is here.
    kept = []
    for para in re.split(r"\n\s*\n", body):
        head = para.strip().lower()
        if any(head.startswith(p) for p in _PREAMBLES):
            continue
        kept.append(para)
    body = "\n\n".join(kept)

    body = " ".join(body.split())
    if not body:
        return ""
    if len(body) > MAX_CHARS:
        # Cut at a word so the line does not end mid-word, but only if there is
        # a word boundary near the end -- otherwise the cut is worse than none.
        cut = body[:MAX_CHARS]
        space = cut.rfind(" ")
        if space > MAX_CHARS - 40:
            cut = cut[:space]
        body = cut.rstrip(" ,;:-") + "…"
    return body


def names_the_work(ask: str) -> bool:
    """Whether a cleaned prompt says what is wanted, rather than agreeing.

    Separate from :func:`the_ask` because the two are different questions and
    only one of them is about cleaning: "ok" survives every clean there is and
    still names nothing.
    """
    words = ask.split()
    if len(words) < MIN_WORDS:
        return False
    # "ok - do it" is an instruction; "ok" and "sure thanks" are not.
    return not all(w.strip(".,!?-").lower() in _ACKNOWLEDGEMENTS for w in words)


def pick_ask(asks: Iterable[str]) -> str:
    """The one prompt from a session worth printing as its goal.

    The first that names the work; failing that, the first there was.  A
    session whose every prompt is "continue" really was a session of saying
    continue, and printing that is more honest than printing nothing.
    """
    first = ""
    for ask in asks:
        if not ask:
            continue
        if not first:
            first = ask
        if names_the_work(ask):
            return ask
    return first


def keep(asks: List[str], ask: str, limit: int = 5) -> None:
    """Record one cleaned prompt against a session, if it is worth keeping.

    Bounded on purpose.  A session runs for hours and the goal is at the top of
    it; keeping every prompt would hold a transcript in memory to print one
    line of it.  The limit is above the number of "ok"s it takes to get to a
    real instruction, which is what the head of a session actually looks like.
    """
    if ask and len(asks) < limit:
        asks.append(ask)
